### ISSUE TITLE
The java files may be corrupt or invalid.

### ISSUE THREAD

**Issue by greusome** [Offline-Cheatbreaker/Offline-CheatBreaker-API#3]
I downloaded this API and I don't know if it's still running or something but when I go to the compiled folders and click the java files they all have the same error message. I would gladly appreciate if someone could help me out! 
![image](https://user-images.githubusercontent.com/82300062/114291405-14fdb100-9a55-11eb-8227-fc0f882eacaa.png)
Also, the latest release's java file doesn't open anything at all.

**Comment by ShonP40** [comment]
You can’t open those files…
Just put them in your server’s plugins folder.
